[project]
name = "tt-stats-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "pathlib>=1.0.1",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
